/*
 * GitProvider
 *
 * This a service contract for the GitProvider in Balsam.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GitProviderApiClient.Client.OpenAPIDateConverter;

namespace GitProviderApiClient.Model
{
    /// <summary>
    /// Branch created description
    /// </summary>
    [DataContract(Name = "BranchCreatedResponse")]
    public partial class BranchCreatedResponse : IEquatable<BranchCreatedResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BranchCreatedResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BranchCreatedResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BranchCreatedResponse" /> class.
        /// </summary>
        /// <param name="repositoryId">The name of the repository. (required).</param>
        /// <param name="id">The id for the branch (required).</param>
        /// <param name="name">The name of the branch (required).</param>
        public BranchCreatedResponse(string repositoryId = default(string), string id = default(string), string name = default(string))
        {
            // to ensure "repositoryId" is required (not null)
            if (repositoryId == null)
            {
                throw new ArgumentNullException("repositoryId is a required property for BranchCreatedResponse and cannot be null");
            }
            this.RepositoryId = repositoryId;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for BranchCreatedResponse and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for BranchCreatedResponse and cannot be null");
            }
            this.Name = name;
        }

        /// <summary>
        /// The name of the repository.
        /// </summary>
        /// <value>The name of the repository.</value>
        [DataMember(Name = "repositoryId", IsRequired = true, EmitDefaultValue = true)]
        public string RepositoryId { get; set; }

        /// <summary>
        /// The id for the branch
        /// </summary>
        /// <value>The id for the branch</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The name of the branch
        /// </summary>
        /// <value>The name of the branch</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BranchCreatedResponse {\n");
            sb.Append("  RepositoryId: ").Append(RepositoryId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BranchCreatedResponse);
        }

        /// <summary>
        /// Returns true if BranchCreatedResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of BranchCreatedResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BranchCreatedResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RepositoryId == input.RepositoryId ||
                    (this.RepositoryId != null &&
                    this.RepositoryId.Equals(input.RepositoryId))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RepositoryId != null)
                {
                    hashCode = (hashCode * 59) + this.RepositoryId.GetHashCode();
                }
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
