/*
 * GitProvider
 *
 * This a service contract for the GitProvider in Balsam.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GitProviderApiClient.Client.OpenAPIDateConverter;

namespace GitProviderApiClient.Model
{
    /// <summary>
    /// Payload for creating new branch
    /// </summary>
    [DataContract(Name = "CreateBranchRequest")]
    public partial class CreateBranchRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateBranchRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateBranchRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateBranchRequest" /> class.
        /// </summary>
        /// <param name="name">The name of the branch (required).</param>
        /// <param name="fromBranch">The branch from which this branch will be created. The default branch for the project will be used if not specified. (required).</param>
        public CreateBranchRequest(string name = default(string), string fromBranch = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateBranchRequest and cannot be null");
            }
            this.Name = name;
            // to ensure "fromBranch" is required (not null)
            if (fromBranch == null)
            {
                throw new ArgumentNullException("fromBranch is a required property for CreateBranchRequest and cannot be null");
            }
            this.FromBranch = fromBranch;
        }

        /// <summary>
        /// The name of the branch
        /// </summary>
        /// <value>The name of the branch</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The branch from which this branch will be created. The default branch for the project will be used if not specified.
        /// </summary>
        /// <value>The branch from which this branch will be created. The default branch for the project will be used if not specified.</value>
        [DataMember(Name = "fromBranch", IsRequired = true, EmitDefaultValue = true)]
        public string FromBranch { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateBranchRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  FromBranch: ").Append(FromBranch).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
