openapi: 3.0.2
info:
  description: This a service contract for the ChatProvider in Balsam.
  title: ChatProvider
  version: "2.0"
servers:
- url: http://chat-provider.balsam-system.svc.cluster.local/api/v1
tags:
- description: Topic methods
  name: Area
paths:
  /areas:
    post:
      description: Creates a new Area
      operationId: CreateArea
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAreaRequest'
        description: Definition of a new area
      responses:
        "200":
          content:
            application/json:
              example:
                name: demo_users
                id: 12
              schema:
                $ref: '#/components/schemas/AreaCreatedResponse'
          description: Success
        "400":
          content:
            application/problem+json:
              example:
                title: Bad Request
                status: 400
                detail: Generic error
              schema:
                $ref: '#/components/schemas/Problem'
          description: Error respsone for 400
      tags:
      - Area
components:
  responses:
    ErrorResponse400:
      content:
        application/problem+json:
          example:
            title: Bad Request
            status: 400
            detail: Generic error
          schema:
            $ref: '#/components/schemas/Problem'
      description: Error respsone for 400
  schemas:
    CreateAreaRequest:
      example:
        name: name
      properties:
        name:
          description: The name of the area
          type: string
      required:
      - name
      type: object
    AreaCreatedResponse:
      description: Group created response
      example:
        name: name
        id: id
      properties:
        name:
          description: The name of the area
          type: string
        id:
          description: The id to the area that can be used for accessing it.
          type: string
      required:
      - id
      - name
      type: object
    Problem:
      properties:
        type:
          default: about:blank
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          example: https://zalando.github.io/problem/constraint-violation
          format: uri
          type: string
        title:
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
          type: string
        status:
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        detail:
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
          type: string
        instance:
          description: "An absolute URI that identifies the specific occurrence of\
            \ the problem.\nIt may or may not yield further information if dereferenced.\n\
            \      \n"
          format: uri
          type: string
      type: object

