additionalProperties:
  aspnetCoreVersion: 6.0
  nullableReferenceTypes: true
  buildTarget: library
  useSwashbuckle: true
  packageName: OicdProvider
  packageTitle: OicdProvider
  packageDescription: OicdProvider class library
  licenseName: MIT
  packageAuthors: SCB