/*
 * BalsamApi
 *
 * This is the API for createing Baslam artifcats.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using BalsamApi.Server.Converters;

namespace BalsamApi.Server.Models
{ 
    /// <summary>
    /// Payload for creating new branch
    /// </summary>
    [DataContract]
    public class CreateKnowledgeLibraryRequest : IEquatable<CreateKnowledgeLibraryRequest>
    {
        /// <summary>
        /// The name of the knowledge library
        /// </summary>
        /// <value>The name of the knowledge library</value>
        [Required]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The desciption of the knowledge library
        /// </summary>
        /// <value>The desciption of the knowledge library</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// The url to the git repository
        /// </summary>
        /// <value>The url to the git repository</value>
        [Required]
        [DataMember(Name="repositoryUrl", EmitDefaultValue=false)]
        public string RepositoryUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateKnowledgeLibraryRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  RepositoryUrl: ").Append(RepositoryUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateKnowledgeLibraryRequest)obj);
        }

        /// <summary>
        /// Returns true if CreateKnowledgeLibraryRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateKnowledgeLibraryRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateKnowledgeLibraryRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    RepositoryUrl == other.RepositoryUrl ||
                    RepositoryUrl != null &&
                    RepositoryUrl.Equals(other.RepositoryUrl)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    if (RepositoryUrl != null)
                    hashCode = hashCode * 59 + RepositoryUrl.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateKnowledgeLibraryRequest left, CreateKnowledgeLibraryRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateKnowledgeLibraryRequest left, CreateKnowledgeLibraryRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
