#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/GitProvider/ && \
    dotnet build src/GitProvider/ && \
    echo "Now, run the following to start the project: dotnet run -p src/GitProvider/GitProvider.csproj --launch-profile web"
