/* tslint:disable */
/* eslint-disable */
/**
 * BalsamApi
 * This is the API for createing Baslam artifcats.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../../base';
// @ts-ignore
import { CreateKnowledgeLibraryRequest } from '../../BalsamAPI/Model';
// @ts-ignore
import { KnowledgeLibrary } from '../../BalsamAPI/Model';
// @ts-ignore
import { KnowledgeLibraryCreatedResponse } from '../../BalsamAPI/Model';
// @ts-ignore
import { Problem } from '../../BalsamAPI/Model';
/**
 * KnowledgeLibraryApi - axios parameter creator
 * @export
 */
export const KnowledgeLibraryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a new connection to a knowledge library
         * @param {CreateKnowledgeLibraryRequest} [createKnowledgeLibraryRequest] Definition of a new Knowledge library connection
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createKnowledgeLibrary: async (createKnowledgeLibraryRequest?: CreateKnowledgeLibraryRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/knowledge-libraries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createKnowledgeLibraryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Removes knowledge library
         * @param {string} libraryId id for the knowledge library
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteKnowledgeLibary: async (libraryId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'libraryId' is not null or undefined
            assertParamExists('deleteKnowledgeLibary', 'libraryId', libraryId)
            const localVarPath = `/knowledge-libraries/{libraryId}`
                .replace(`{${"libraryId"}}`, encodeURIComponent(String(libraryId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List available knowledge Libraries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listKnowledgeLibaries: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/knowledge-libraries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * KnowledgeLibraryApi - functional programming interface
 * @export
 */
export const KnowledgeLibraryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = KnowledgeLibraryApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a new connection to a knowledge library
         * @param {CreateKnowledgeLibraryRequest} [createKnowledgeLibraryRequest] Definition of a new Knowledge library connection
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createKnowledgeLibrary(createKnowledgeLibraryRequest?: CreateKnowledgeLibraryRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KnowledgeLibraryCreatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createKnowledgeLibrary(createKnowledgeLibraryRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Removes knowledge library
         * @param {string} libraryId id for the knowledge library
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteKnowledgeLibary(libraryId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteKnowledgeLibary(libraryId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * List available knowledge Libraries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listKnowledgeLibaries(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<KnowledgeLibrary>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listKnowledgeLibaries(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * KnowledgeLibraryApi - factory interface
 * @export
 */
export const KnowledgeLibraryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = KnowledgeLibraryApiFp(configuration)
    return {
        /**
         * Create a new connection to a knowledge library
         * @param {CreateKnowledgeLibraryRequest} [createKnowledgeLibraryRequest] Definition of a new Knowledge library connection
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createKnowledgeLibrary(createKnowledgeLibraryRequest?: CreateKnowledgeLibraryRequest, options?: any): AxiosPromise<KnowledgeLibraryCreatedResponse> {
            return localVarFp.createKnowledgeLibrary(createKnowledgeLibraryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Removes knowledge library
         * @param {string} libraryId id for the knowledge library
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteKnowledgeLibary(libraryId: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteKnowledgeLibary(libraryId, options).then((request) => request(axios, basePath));
        },
        /**
         * List available knowledge Libraries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listKnowledgeLibaries(options?: any): AxiosPromise<Array<KnowledgeLibrary>> {
            return localVarFp.listKnowledgeLibaries(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * KnowledgeLibraryApi - object-oriented interface
 * @export
 * @class KnowledgeLibraryApi
 * @extends {BaseAPI}
 */
export class KnowledgeLibraryApi extends BaseAPI {
    /**
     * Create a new connection to a knowledge library
     * @param {CreateKnowledgeLibraryRequest} [createKnowledgeLibraryRequest] Definition of a new Knowledge library connection
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KnowledgeLibraryApi
     */
    public createKnowledgeLibrary(createKnowledgeLibraryRequest?: CreateKnowledgeLibraryRequest, options?: AxiosRequestConfig) {
        return KnowledgeLibraryApiFp(this.configuration).createKnowledgeLibrary(createKnowledgeLibraryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Removes knowledge library
     * @param {string} libraryId id for the knowledge library
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KnowledgeLibraryApi
     */
    public deleteKnowledgeLibary(libraryId: string, options?: AxiosRequestConfig) {
        return KnowledgeLibraryApiFp(this.configuration).deleteKnowledgeLibary(libraryId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List available knowledge Libraries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KnowledgeLibraryApi
     */
    public listKnowledgeLibaries(options?: AxiosRequestConfig) {
        return KnowledgeLibraryApiFp(this.configuration).listKnowledgeLibaries(options).then((request) => request(this.axios, this.basePath));
    }
}

