/*
 * S3Provider
 *
 * This a service contract for the OicdProvider in Balsam.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using S3ProviderApiClient.Model;
using S3ProviderApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace S3ProviderApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AccessKeyCreatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccessKeyCreatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccessKeyCreatedResponse
        //private AccessKeyCreatedResponse instance;

        public AccessKeyCreatedResponseTests()
        {
            // TODO uncomment below to create an instance of AccessKeyCreatedResponse
            //instance = new AccessKeyCreatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccessKeyCreatedResponse
        /// </summary>
        [Fact]
        public void AccessKeyCreatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccessKeyCreatedResponse
            //Assert.IsType<AccessKeyCreatedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'AccessKey'
        /// </summary>
        [Fact]
        public void AccessKeyTest()
        {
            // TODO unit test for the property 'AccessKey'
        }

        /// <summary>
        /// Test the property 'SecretKey'
        /// </summary>
        [Fact]
        public void SecretKeyTest()
        {
            // TODO unit test for the property 'SecretKey'
        }
    }
}
