/*
 * S3Provider
 *
 * This a service contract for the OicdProvider in Balsam.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using S3ProviderApiClient.Model;
using S3ProviderApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace S3ProviderApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CreateBucketRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateBucketRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateBucketRequest
        //private CreateBucketRequest instance;

        public CreateBucketRequestTests()
        {
            // TODO uncomment below to create an instance of CreateBucketRequest
            //instance = new CreateBucketRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateBucketRequest
        /// </summary>
        [Fact]
        public void CreateBucketRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateBucketRequest
            //Assert.IsType<CreateBucketRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
