/*
 * GitProvider
 *
 * This a service contract for the GitProvider in Balsam.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using S3ProviderApiClient.Model;
using S3ProviderApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace S3ProviderApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing RepositoryCreatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RepositoryCreatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RepositoryCreatedResponse
        //private RepositoryCreatedResponse instance;

        public RepositoryCreatedResponseTests()
        {
            // TODO uncomment below to create an instance of RepositoryCreatedResponse
            //instance = new RepositoryCreatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RepositoryCreatedResponse
        /// </summary>
        [Fact]
        public void RepositoryCreatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RepositoryCreatedResponse
            //Assert.IsType<RepositoryCreatedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'PreferredName'
        /// </summary>
        [Fact]
        public void PreferredNameTest()
        {
            // TODO unit test for the property 'PreferredName'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
    }
}
