/*
 * ChatProvider
 *
 * This a service contract for the ChatProvider in Balsam.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RocketChatChatProviderApiClient.Model;
using RocketChatChatProviderApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RocketChatChatProviderApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AreaCreatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AreaCreatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AreaCreatedResponse
        //private AreaCreatedResponse instance;

        public AreaCreatedResponseTests()
        {
            // TODO uncomment below to create an instance of AreaCreatedResponse
            //instance = new AreaCreatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AreaCreatedResponse
        /// </summary>
        [Fact]
        public void AreaCreatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AreaCreatedResponse
            //Assert.IsType<AreaCreatedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
