:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\OicdProvider
dotnet build src\OicdProvider
echo Now, run the following to start the project: dotnet run -p src\OicdProvider\OicdProvider.csproj --launch-profile web.
echo.
