apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{Branch.Id}}-{{Workspace.Id}}-pvc-elyra-claim
  namespace: proj-{{Project.Id}}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
