/*
 * ChatProvider
 *
 * This a service contract for the ChatProvider in Balsam.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using RocketChatChatProviderApiClient.Client;
using RocketChatChatProviderApiClient.Model;

namespace RocketChatChatProviderApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAreaApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a new Area
        /// </remarks>
        /// <exception cref="RocketChatChatProviderApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAreaRequest">Definition of a new area (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AreaCreatedResponse</returns>
        AreaCreatedResponse CreateArea(CreateAreaRequest? createAreaRequest = default(CreateAreaRequest?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a new Area
        /// </remarks>
        /// <exception cref="RocketChatChatProviderApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAreaRequest">Definition of a new area (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AreaCreatedResponse</returns>
        ApiResponse<AreaCreatedResponse> CreateAreaWithHttpInfo(CreateAreaRequest? createAreaRequest = default(CreateAreaRequest?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAreaApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a new Area
        /// </remarks>
        /// <exception cref="RocketChatChatProviderApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAreaRequest">Definition of a new area (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AreaCreatedResponse</returns>
        System.Threading.Tasks.Task<AreaCreatedResponse> CreateAreaAsync(CreateAreaRequest? createAreaRequest = default(CreateAreaRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates a new Area
        /// </remarks>
        /// <exception cref="RocketChatChatProviderApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAreaRequest">Definition of a new area (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AreaCreatedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AreaCreatedResponse>> CreateAreaWithHttpInfoAsync(CreateAreaRequest? createAreaRequest = default(CreateAreaRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAreaApi : IAreaApiSync, IAreaApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AreaApi : IAreaApi
    {
        private RocketChatChatProviderApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AreaApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AreaApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AreaApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AreaApi(string basePath)
        {
            this.Configuration = RocketChatChatProviderApiClient.Client.Configuration.MergeConfigurations(
                RocketChatChatProviderApiClient.Client.GlobalConfiguration.Instance,
                new RocketChatChatProviderApiClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new RocketChatChatProviderApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new RocketChatChatProviderApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = RocketChatChatProviderApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AreaApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AreaApi(RocketChatChatProviderApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = RocketChatChatProviderApiClient.Client.Configuration.MergeConfigurations(
                RocketChatChatProviderApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new RocketChatChatProviderApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new RocketChatChatProviderApiClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = RocketChatChatProviderApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AreaApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AreaApi(RocketChatChatProviderApiClient.Client.ISynchronousClient client, RocketChatChatProviderApiClient.Client.IAsynchronousClient asyncClient, RocketChatChatProviderApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = RocketChatChatProviderApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public RocketChatChatProviderApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public RocketChatChatProviderApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public RocketChatChatProviderApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public RocketChatChatProviderApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Creates a new Area
        /// </summary>
        /// <exception cref="RocketChatChatProviderApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAreaRequest">Definition of a new area (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AreaCreatedResponse</returns>
        public AreaCreatedResponse CreateArea(CreateAreaRequest? createAreaRequest = default(CreateAreaRequest?), int operationIndex = 0)
        {
            RocketChatChatProviderApiClient.Client.ApiResponse<AreaCreatedResponse> localVarResponse = CreateAreaWithHttpInfo(createAreaRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Creates a new Area
        /// </summary>
        /// <exception cref="RocketChatChatProviderApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAreaRequest">Definition of a new area (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AreaCreatedResponse</returns>
        public RocketChatChatProviderApiClient.Client.ApiResponse<AreaCreatedResponse> CreateAreaWithHttpInfo(CreateAreaRequest? createAreaRequest = default(CreateAreaRequest?), int operationIndex = 0)
        {
            RocketChatChatProviderApiClient.Client.RequestOptions localVarRequestOptions = new RocketChatChatProviderApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = RocketChatChatProviderApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = RocketChatChatProviderApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = createAreaRequest;

            localVarRequestOptions.Operation = "AreaApi.CreateArea";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<AreaCreatedResponse>("/areas", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateArea", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Creates a new Area
        /// </summary>
        /// <exception cref="RocketChatChatProviderApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAreaRequest">Definition of a new area (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AreaCreatedResponse</returns>
        public async System.Threading.Tasks.Task<AreaCreatedResponse> CreateAreaAsync(CreateAreaRequest? createAreaRequest = default(CreateAreaRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            RocketChatChatProviderApiClient.Client.ApiResponse<AreaCreatedResponse> localVarResponse = await CreateAreaWithHttpInfoAsync(createAreaRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Creates a new Area
        /// </summary>
        /// <exception cref="RocketChatChatProviderApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAreaRequest">Definition of a new area (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AreaCreatedResponse)</returns>
        public async System.Threading.Tasks.Task<RocketChatChatProviderApiClient.Client.ApiResponse<AreaCreatedResponse>> CreateAreaWithHttpInfoAsync(CreateAreaRequest? createAreaRequest = default(CreateAreaRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            RocketChatChatProviderApiClient.Client.RequestOptions localVarRequestOptions = new RocketChatChatProviderApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = RocketChatChatProviderApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = RocketChatChatProviderApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = createAreaRequest;

            localVarRequestOptions.Operation = "AreaApi.CreateArea";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<AreaCreatedResponse>("/areas", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateArea", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
