apiVersion: apps/v1
kind: Deployment
metadata:
  name: balsam-ui
  labels:
    app: balsam-ui
  namespace: balsam-system
spec:
  replicas: {{ .Values.replicaCount }} #En gemensam replicaCount för att styra alla api:er, kan ändras
  selector:
    matchLabels:
      app: balsam-ui
  template:
    metadata:
      labels:
        app: balsam-ui
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      containers:
      - name: balsam-ui
        image: "{{ .Values.balsamUi.image.repository }}:{{ .Values.balsamUi.image.tag }}"
        imagePullPolicy: {{ .Values.balsamUi.image.pullPolicy }}
        volumeMounts:
          - name: {{ .Values.balsamUi.configMap.name }}
            mountPath: "/usr/share/nginx/html/config.json"
            readOnly: true
            subPath: config.json
          - name: {{ .Values.balsamUi.configMap.name }}
            mountPath: "/usr/share/nginx/html/keycloak.json"
            readOnly: true
            subPath: keycloak.json
          - name: {{.Values.balsamUi.configMap.name }}
            mountPath: "/etc/nginx/conf.d/default.conf"
            readOnly: true
            subPath: default.conf
        resources:
          requests:
            memory: "200Mi"
            cpu: "500m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.balsamUi.containerPort }}
      volumes:
        - name: {{ .Values.balsamUi.configMap.name }}
          configMap:
            name: {{ .Values.balsamUi.configMap.name }}