apiVersion: v1
kind: Service
metadata:
  name: balsam-ui
  namespace: balsam-system
spec:
  type: {{ .Values.balsamUi.service.type }}
  selector:
    app: balsam-ui
  ports:
    - protocol: TCP
      port: {{ .Values.balsamUi.service.port }}
      targetPort: {{ .Values.balsamUi.containerPort }}