apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.balsamApi.configMap.name }}
  namespace: balsam-system
data: 
  HubRepo__RemoteUrl: "{{ .Values.balsamApi.configMap.data.repoUrl }}"
  Authentication__Authority: "{{ .Values.balsamApi.configMap.data.authority}}"