apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.balsamApi.secret.name | indent 2 }}
  namespace: balsam-system
type: Opaque
data:
  HubRepo__User: {{ .Values.balsamApi.secret.data.user | b64enc }}
  HubRepo__Password: {{ .Values.balsamApi.secret.data.password | b64enc }}