{{- if .Values.chatProvider.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: chat-provider
  namespace: balsam-system
spec:
  type: {{ .Values.chatProvider.service.type }}
  selector:
    app: rocketchat-provider
  ports:
    - protocol: TCP
      port: {{ .Values.chatProvider.service.port }}
      targetPort: {{ .Values.chatProvider.containerPort }}
{{- end }}