{{- if .Values.chatProvider.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.chatProvider.configMap.name }}
  namespace: balsam-system
data: 
  API__BaseUrl: "{{ .Values.chatProvider.configMap.data.API__BaseUrl }}"
  API__UserId: {{ .Values.chatProvider.configMap.data.API__UserId }}
{{- end }}