{{- if .Values.chatProvider.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.chatProvider.secret.name }}
  namespace: balsam-system
type: Opaque
data:
  API__Token: {{ .Values.chatProvider.secret.data.API__Token | b64enc }}
{{- end }}