apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oidcProvider.secret.name }}
  namespace: balsam-system
data: 
  KEYCLOAK__ClientSecret: "{{ .Values.oidcProvider.secret.data.KEYCLOAK__ClientSecret | b64enc }}"
  KEYCLOAK__User: {{ .Values.oidcProvider.secret.data.KEYCLOAK__User | b64enc }}
  KEYCLOAK__Password: {{ .Values.oidcProvider.secret.data.KEYCLOAK__Password | b64enc }}