apiVersion: v1
kind: Service
metadata:
  name: oidc-provider
  namespace: balsam-system
spec:
  type: {{ .Values.oidcProvider.service.type }}
  selector:
    app: oidc-provider
  ports:
    - protocol: TCP
      port: {{ .Values.oidcProvider.service.port }}
      targetPort: {{ .Values.oidcProvider.containerPort }}