/*
 * GitProvider
 *
 * This a service contract for the GitProvider in Balsam.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GitProviderApiClient.Model;
using GitProviderApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GitProviderApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing BranchCreatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BranchCreatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BranchCreatedResponse
        //private BranchCreatedResponse instance;

        public BranchCreatedResponseTests()
        {
            // TODO uncomment below to create an instance of BranchCreatedResponse
            //instance = new BranchCreatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BranchCreatedResponse
        /// </summary>
        [Fact]
        public void BranchCreatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BranchCreatedResponse
            //Assert.IsType<BranchCreatedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'RepositoryId'
        /// </summary>
        [Fact]
        public void RepositoryIdTest()
        {
            // TODO unit test for the property 'RepositoryId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
