/*
 * GitProvider
 *
 * This a service contract for the GitProvider in Balsam.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GitProviderApiClient.Model;
using GitProviderApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GitProviderApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing File
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for File
        //private File instance;

        public FileTests()
        {
            // TODO uncomment below to create an instance of File
            //instance = new File();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of File
        /// </summary>
        [Fact]
        public void FileInstanceTest()
        {
            // TODO uncomment below to test "IsType" File
            //Assert.IsType<File>(instance);
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'ContentUrl'
        /// </summary>
        [Fact]
        public void ContentUrlTest()
        {
            // TODO unit test for the property 'ContentUrl'
        }
    }
}
