/*
 * GitProvider
 *
 * This a service contract for the GitProvider in Balsam.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GitProviderApiClient.Model;
using GitProviderApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GitProviderApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing RepoFile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RepoFileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RepoFile
        //private RepoFile instance;

        public RepoFileTests()
        {
            // TODO uncomment below to create an instance of RepoFile
            //instance = new RepoFile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RepoFile
        /// </summary>
        [Fact]
        public void RepoFileInstanceTest()
        {
            // TODO uncomment below to test "IsType" RepoFile
            //Assert.IsType<RepoFile>(instance);
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'ContentUrl'
        /// </summary>
        [Fact]
        public void ContentUrlTest()
        {
            // TODO unit test for the property 'ContentUrl'
        }
    }
}
