#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/BalsamApi.Server/ && \
    dotnet build src/BalsamApi.Server/ && \
    echo "Now, run the following to start the project: dotnet run -p src/BalsamApi.Server/BalsamApi.Server.csproj --launch-profile web"
