#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/S3Provider/ && \
    dotnet build src/S3Provider/ && \
    echo "Now, run the following to start the project: dotnet run -p src/S3Provider/S3Provider.csproj --launch-profile web"
