/*
 * OidcProvider
 *
 * This a service contract for the OidcProvider in Balsam.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OidcProviderApiClient.Model;
using OidcProviderApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OidcProviderApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AddUserToGroupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddUserToGroupRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddUserToGroupRequest
        //private AddUserToGroupRequest instance;

        public AddUserToGroupRequestTests()
        {
            // TODO uncomment below to create an instance of AddUserToGroupRequest
            //instance = new AddUserToGroupRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddUserToGroupRequest
        /// </summary>
        [Fact]
        public void AddUserToGroupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddUserToGroupRequest
            //Assert.IsType<AddUserToGroupRequest>(instance);
        }

        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
    }
}
