/* tslint:disable */
/* eslint-disable */
/**
 * BalsamApi
 * This is the API for createing Baslam artifcats.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Branch created response
 * @export
 * @interface BranchCreatedResponse
 */
export interface BranchCreatedResponse {
    /**
     * The identifier
     * @type {string}
     * @memberof BranchCreatedResponse
     */
    'id': string;
    /**
     * The identifier for the project
     * @type {string}
     * @memberof BranchCreatedResponse
     */
    'projectId': string;
    /**
     * The branch name
     * @type {string}
     * @memberof BranchCreatedResponse
     */
    'name': string;
}

