/* tslint:disable */
/* eslint-disable */
/**
 * BalsamApi
 * This is the API for createing Baslam artifcats.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Payload for creating new branch
 * @export
 * @interface CreateWorkspaceRequest
 */
export interface CreateWorkspaceRequest {
    /**
     * The name of the workspace
     * @type {string}
     * @memberof CreateWorkspaceRequest
     */
    'name': string;
    /**
     * The id of the template
     * @type {string}
     * @memberof CreateWorkspaceRequest
     */
    'templateId': string;
    /**
     * The id of the project
     * @type {string}
     * @memberof CreateWorkspaceRequest
     */
    'projectId': string;
    /**
     * The id of the branch
     * @type {string}
     * @memberof CreateWorkspaceRequest
     */
    'branchId': string;
}

