/* tslint:disable */
/* eslint-disable */
/**
 * BalsamApi
 * This is the API for createing Baslam artifcats.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Payload for creating new branch
 * @export
 * @interface CreateBranchRequest
 */
export interface CreateBranchRequest {
    /**
     * The name of the branch
     * @type {string}
     * @memberof CreateBranchRequest
     */
    'name': string;
    /**
     * The description of the branch
     * @type {string}
     * @memberof CreateBranchRequest
     */
    'description'?: string;
    /**
     * The branch from which this branch will be created. The default branch for the project will be used if not specified.
     * @type {string}
     * @memberof CreateBranchRequest
     */
    'fromBranch'?: string;
}

