/* tslint:disable */
/* eslint-disable */
/**
 * BalsamApi
 * This is the API for createing Baslam artifcats.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Payload for creating new project
 * @export
 * @interface CreateProjectRequest
 */
export interface CreateProjectRequest {
    /**
     * The name
     * @type {string}
     * @memberof CreateProjectRequest
     */
    'name': string;
    /**
     * The description of the project
     * @type {string}
     * @memberof CreateProjectRequest
     */
    'description'?: string;
    /**
     * Name of the default branch
     * @type {string}
     * @memberof CreateProjectRequest
     */
    'branchName': string;
}

