/* tslint:disable */
/* eslint-disable */
/**
 * BalsamApi
 * This is the API for createing Baslam artifcats.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Workspace template
 * @export
 * @interface Template
 */
export interface Template {
    /**
     * The identifier
     * @type {string}
     * @memberof Template
     */
    'id': string;
    /**
     * The name
     * @type {string}
     * @memberof Template
     */
    'name': string;
    /**
     * Description of the template
     * @type {string}
     * @memberof Template
     */
    'description'?: string;
}

