/* tslint:disable */
/* eslint-disable */
/**
 * BalsamApi
 * This is the API for createing Baslam artifcats.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Workspace
 */
export interface Workspace {
    /**
     * The identifier
     * @type {string}
     * @memberof Workspace
     */
    'id': string;
    /**
     * The name
     * @type {string}
     * @memberof Workspace
     */
    'name': string;
    /**
     * The id of the template that the workspace is based on.
     * @type {string}
     * @memberof Workspace
     */
    'templateId': string;
    /**
     * The id of the project
     * @type {string}
     * @memberof Workspace
     */
    'projectId': string;
    /**
     * The id of the branch
     * @type {string}
     * @memberof Workspace
     */
    'branchId': string;
}

