/*
 * S3Provider
 *
 * This a service contract for the OicdProvider in Balsam.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = S3ProviderApiClient.Client.OpenAPIDateConverter;

namespace S3ProviderApiClient.Model
{
    /// <summary>
    /// Access key created description
    /// </summary>
    [DataContract(Name = "AccessKeyCreatedResponse")]
    public partial class AccessKeyCreatedResponse : IEquatable<AccessKeyCreatedResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccessKeyCreatedResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccessKeyCreatedResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccessKeyCreatedResponse" /> class.
        /// </summary>
        /// <param name="accessKey">The access key (required).</param>
        /// <param name="secretKey">The secret key (required).</param>
        /// <param name="apiUrl">URL to the API. (required).</param>
        public AccessKeyCreatedResponse(string accessKey = default(string), string secretKey = default(string), string apiUrl = default(string))
        {
            // to ensure "accessKey" is required (not null)
            if (accessKey == null)
            {
                throw new ArgumentNullException("accessKey is a required property for AccessKeyCreatedResponse and cannot be null");
            }
            this.AccessKey = accessKey;
            // to ensure "secretKey" is required (not null)
            if (secretKey == null)
            {
                throw new ArgumentNullException("secretKey is a required property for AccessKeyCreatedResponse and cannot be null");
            }
            this.SecretKey = secretKey;
            // to ensure "apiUrl" is required (not null)
            if (apiUrl == null)
            {
                throw new ArgumentNullException("apiUrl is a required property for AccessKeyCreatedResponse and cannot be null");
            }
            this.ApiUrl = apiUrl;
        }

        /// <summary>
        /// The access key
        /// </summary>
        /// <value>The access key</value>
        [DataMember(Name = "accessKey", IsRequired = true, EmitDefaultValue = true)]
        public string AccessKey { get; set; }

        /// <summary>
        /// The secret key
        /// </summary>
        /// <value>The secret key</value>
        [DataMember(Name = "secretKey", IsRequired = true, EmitDefaultValue = true)]
        public string SecretKey { get; set; }

        /// <summary>
        /// URL to the API.
        /// </summary>
        /// <value>URL to the API.</value>
        [DataMember(Name = "apiUrl", IsRequired = true, EmitDefaultValue = true)]
        public string ApiUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccessKeyCreatedResponse {\n");
            sb.Append("  AccessKey: ").Append(AccessKey).Append("\n");
            sb.Append("  SecretKey: ").Append(SecretKey).Append("\n");
            sb.Append("  ApiUrl: ").Append(ApiUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AccessKeyCreatedResponse);
        }

        /// <summary>
        /// Returns true if AccessKeyCreatedResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of AccessKeyCreatedResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AccessKeyCreatedResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AccessKey == input.AccessKey ||
                    (this.AccessKey != null &&
                    this.AccessKey.Equals(input.AccessKey))
                ) && 
                (
                    this.SecretKey == input.SecretKey ||
                    (this.SecretKey != null &&
                    this.SecretKey.Equals(input.SecretKey))
                ) && 
                (
                    this.ApiUrl == input.ApiUrl ||
                    (this.ApiUrl != null &&
                    this.ApiUrl.Equals(input.ApiUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AccessKey != null)
                {
                    hashCode = (hashCode * 59) + this.AccessKey.GetHashCode();
                }
                if (this.SecretKey != null)
                {
                    hashCode = (hashCode * 59) + this.SecretKey.GetHashCode();
                }
                if (this.ApiUrl != null)
                {
                    hashCode = (hashCode * 59) + this.ApiUrl.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
