# Default values for balsam-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

balsamApi:
  image:
    repository: # The repository for balsamApi
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.0.20 # The tag for balsamApi
  service:
    type: ClusterIP
    port: 80
  containerPort: 8080
  secret:
    name: balsam-api-secret
    data:
      user: ##The serviceAccount to modify the hubrepo
      password: ##The password/PAT of the serviceaccount
  configMap:
    name: balsam-api-config
    data:
      repoUrl: ##The URL for the hubrepo with protocol e.g. http/https
      authority: 
  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: "contour",
      cert-manager.io/cluster-issuer: ca-issuer,
      kubernetes.io/ingress.allow-http: "true"
    }
    hosts:
      host: # Add the ingress for balsamApi


s3Provider:
  image:
    repository: # The repository for the s3Provider API
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.0.2 # The tag for the s3Provider API
  service:
    type: ClusterIP
    port: 80
  containerPort: 8080
  secret:
    name: minio-s3-provider-secret
    data:
      API__ACCESSKEY: # The API Access Key used by the S3 Provider
      API__SECRETKEY: # The API Secret Key used by the S3 Provider
  configMap:
    name: minio-s3-provider-config
    data:
      API__DOMAIN: # The Ingress for the S3 API
      API__PROTOCOL: http

oidcProvider:
  image:
    repository: # The repository for the oidcProvider API
    pullPolicy: Always
    tag: 0.0.5
  service:
    type: ClusterIP
    port: 80
  containerPort: 8080
  secret:
    name: keycloak-provider-secret
    data:
      KEYCLOAK__ClientSecret: ""
      KEYCLOAK__User: ""
      KEYCLOAK__Password: ""
  configMap:
    name: keycloak-provider-config
    data:
      KEYCLOAK__BaseUrl: ""
      KEYCLOAK__Realm: ""
      KEYCLOAK__ClientId: ""

gitProvider:
  image:
    repository: # The repository for the gitProvider API
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.0.5 # The tag for the gitProvider API
  service:
    type: ClusterIP
    port: 80
  containerPort: 8080
  secret:
    name: gitlab-provider-secret
    data:
      API__PAT: # The PAT used by the gitprovider API
  configMap:
    name: gitlab-provider-config
    data:
      API__GroupID: # The GroupID (GitLab)
      API__BaseUrl: # The baseURL for the GitLab instance
      API__TemplatePath: /app/templates

serviceAccount:
  # Specifies whether a service account should be created
  enabled: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: balsam-sa

roleBinding:
  enabled: false
  roleRef: psp:vmware-system-restricted

# Run as non-root
securityContext: {
    runAsUser: 1000,
    fsGroup: 2000,
    runAsGroup: 3000
}

# service:
#   type: ClusterIP
#   port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi